import { z } from 'zod'; import type { Minigame, MinigameConfig, MinigameContext, MinigameOutcome } from './contract';
interface State { mpcId:string; supportIds:string[]; lane:number; plushLane:number; badLane:number; caught:number; needed:number; shields:number; deadline:number; outcome:'pending'|'success'|'bad'|'timeout'; }
const actionSchema=z.object({kind:z.enum(['move','catch','shield']),lane:z.number().int().min(0).max(4)}); const asState=(v:unknown)=>v as State; const lane=(r:()=>number)=>Math.floor(r()*5);
export const plushCatchGame: Minigame={id:'plush_catch',title:'Catch the Falling Plushies',actionSchema,
createInitialState(c:MinigameConfig,ctx:MinigameContext):State { const plushLane=lane(ctx.random); let badLane=lane(ctx.random); if(badLane===plushLane)badLane=(badLane+1)%5; return {mpcId:c.mpcId,supportIds:c.supportIds,lane:2,plushLane,badLane,caught:0,needed:Math.min(8,3+c.difficulty),shields:0,deadline:0,outcome:'pending'};},
onStart(v,ctx){const s=asState(v);return {...s,deadline:ctx.now+26_000};},
handleMpcAction(v,a,ctx){const s=asState(v),x=a as z.infer<typeof actionSchema>;if(s.outcome!=='pending')return s;if(x.kind==='move')return {...s,lane:x.lane};if(x.kind!=='catch'||x.lane!==s.lane)return s;if(s.lane===s.badLane&&s.shields===0)return {...s,outcome:'bad'};if(s.lane!==s.plushLane)return s;const caught=s.caught+1;if(caught>=s.needed)return {...s,caught,outcome:'success'};const plushLane=lane(ctx.random);let badLane=lane(ctx.random);if(badLane===plushLane)badLane=(badLane+1)%5;return {...s,caught,plushLane,badLane};},
handleSupportAction(v,id,a){const s=asState(v),x=a as z.infer<typeof actionSchema>;return s.outcome==='pending'&&s.supportIds.includes(id)&&x.kind==='shield'&&x.lane===s.badLane?{...s,shields:s.shields+1}:s;},onDeadline(v,ctx){const s=asState(v);return s.outcome==='pending'&&ctx.now>=s.deadline?{...s,outcome:'timeout'}:s;},
evaluate(v):MinigameOutcome{const s=asState(v);return s.outcome==='success'?{status:'resolved',success:true,headline:`Caught ${s.caught} plushies with ${s.shields} shield(s)!`}:s.outcome==='bad'?{status:'resolved',success:false,headline:'A bad object hit the basket!'}:s.outcome==='timeout'?{status:'resolved',success:false,headline:'Too many plushies fell away.'}:{status:'active'};},getNextDeadline(v){const s=asState(v);return s.outcome==='pending'?s.deadline:null;},getFuse(v){const s=asState(v);return s.outcome==='pending'?{deadlineAt:s.deadline,totalMs:26_000}:null;},getStateForPlayer(v,id){const s=asState(v),role=id===s.mpcId?'mpc':s.supportIds.includes(id)?'support':'spectator';return {role,lane:s.lane,plushLane:role==='mpc'?s.plushLane:null,badLane:role==='support'?s.badLane:null,caught:s.caught,needed:s.needed,shields:s.shields};}};
